### ISSUE TITLE
How can I reduce GPU memory consumption？

### ISSUE THREAD

**Issue by wuwenbin970731** [okotaku/diffengine#55]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

I started training on **2080Ti GPU**, but encoutered OOM error, how can I reduce the memory consumption to solve it?

The training command is 

```python
 mim train diffengine stable_diffusion_v15_dreambooth_lora_dog.py \
  --cfg-options train_dataloader.dataset.class_image_config.num_images=50 \
  train_dataloader.batch_size=1 \
  train_dataloader.dataset.class_image_config.recreate_class_images=False \
  train_cfg.max_iters=1000 \
  optim_wrapper.type='AmpOptimWrapper' \
  optim_wrapper.dtype='float16' \
  optim_wrapper.optimizer.lr=1e-4 \
  model.lora_config.rank=8
```

The error message is 

```bash
RuntimeError: class `IterBasedTrainLoop` in mmengine/runner/loops.py: class `HFDreamBoothDataset` in diffengine/datasets/hf_dreambooth_d│$
atasets.py: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 10.75 GiB total capacity; 9.07 GiB already allocated; 248.50 MiB f│
ree; 9.20 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentati│
on.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by okotaku** [comment]
@wuwenbin970731 You can try using model.gradient_checkpointing=True. In my experiments, it reduced memory usage from 8473MiB to 5989MiB.

```
mim train diffengine stable_diffusion_v15_dreambooth_lora_dog.py \
  --cfg-options train_dataloader.dataset.class_image_config.num_images=50 \
  train_dataloader.batch_size=1 \
  train_dataloader.dataset.class_image_config.recreate_class_images=False \
  train_cfg.max_iters=1000 \
  optim_wrapper.type='AmpOptimWrapper' \
  optim_wrapper.dtype='float16' \
  optim_wrapper.optimizer.lr=1e-4 \
  model.lora_config.rank=8 model.gradient_checkpointing=True
```

**Comment by wuwenbin970731** [comment]
Thanks for your reply. I set `model.gradient_checkpointing=True`, but still encounter OOM error. 

The OOM error is invoked at HFDreamBoothDataset, I am not familiar with SD, why it would use GPU in Dataset? Could I avoid using it?

**Comment by wuwenbin970731** [comment]
Thanks, it works. I will learn more about stable diffusion later.
Thanks for your great work.
